create sequence hibernate_sequence start 1 increment 1;
create table roles (id int4 not null, name varchar(20), primary key (id));
create table tarefas (id int4 not null, data_entrega date, ds_tarefa varchar(150) not null, status varchar(255), visivel boolean not null, categoria_id int4 not null, usuario_id int4 not null, primary key (id));
create table tarefas_categoria (id int4 not null, nome varchar(50), primary key (id));
create table usuarios (id int4 not null, nome varchar(255), senha varchar(255), primary key (id));
create table usuarios_roles (usuario_id int4 not null, role_id int4 not null, primary key (usuario_id, role_id));
alter table if exists tarefas add constraint FK7gbs6oj78aa9g3wnx8tx1gfi foreign key (categoria_id) references tarefas_categoria;
alter table if exists tarefas add constraint FK2vwr1gcbcpkerkhk9ktxxbep foreign key (usuario_id) references usuarios;
alter table if exists usuarios_roles add constraint FKihom0uklpkfpffipxpoyf7b74 foreign key (role_id) references roles;
alter table if exists usuarios_roles add constraint FKqcxu02bqipxpr7cjyj9dmhwec foreign key (usuario_id) references usuarios;
create sequence hibernate_sequence start 1 increment 1;
create table roles (id int4 not null, name varchar(20), primary key (id));
create table tarefas (id int4 not null, data_entrega date, ds_tarefa varchar(150) not null, status varchar(255), visivel boolean not null, categoria_id int4 not null, usuario_id int4 not null, primary key (id));
create table tarefas_categoria (id int4 not null, nome varchar(50), primary key (id));
create table usuarios (id int4 not null, nome varchar(255), senha varchar(255), primary key (id));
create table usuarios_roles (usuario_id int4 not null, role_id int4 not null, primary key (usuario_id, role_id));
alter table if exists tarefas add constraint FK7gbs6oj78aa9g3wnx8tx1gfi foreign key (categoria_id) references tarefas_categoria;
alter table if exists tarefas add constraint FK2vwr1gcbcpkerkhk9ktxxbep foreign key (usuario_id) references usuarios;
alter table if exists usuarios_roles add constraint FKihom0uklpkfpffipxpoyf7b74 foreign key (role_id) references roles;
alter table if exists usuarios_roles add constraint FKqcxu02bqipxpr7cjyj9dmhwec foreign key (usuario_id) references usuarios;
